### ISSUE TITLE
Found a problem with locations defined in createPublicArchiveTransaction

### ISSUE THREAD

**Issue by mattcui** [maximilien/softlayer-go#102]
Found a problem with locations defined in [createPublicArchiveTransaction](https://github.com/maximilien/softlayer-go/blob/master/services/softLayer_virtual_guest_block_device_template_group.go#L402)
Below is the parameter list generated for createPublicArchiveTransaction function currently:
```json
{"parameters":["light-bosh-stemcell-3232.3-softlayer-esxi-ubuntu-trusty-go_agent","Public_light_stemcell_3232.3","Public_light_stemcell_3232.3",[358694,449494]]}
```

But the format of location list is wrong, it should be like:
```json
    [
      {
         "id":358694
      },
      {
         "id":358694
      }
    ]
```

**Comment by mattcui** [comment]
@maximilien  I got the idea on how to fix it, it's very easy, just use "[]datatypes.SoftLayer_Location", don't need to parse it to retrieve id of each DC. I will submit a PR right now.

**Comment by mattcui** [comment]
@maximilien  I submitted [PR 104](https://github.com/maximilien/softlayer-go/pull/104), please review. Thank you.

**Comment by maximilien** [comment]
Cool. Thanks 👍
