### ISSUE TITLE
Need to support to set multiple http codes in http_client_fake

### ISSUE THREAD

**Issue by mattcui** [maximilien/softlayer-go#111]
@maximilien During writing unit test for [FindById](https://github.com/mattcui/bosh-softlayer-cpi/blob/find_stemcell/softlayer/stemcell/softlayer_finder_test.go#L52), I found there is no way to set http code multiple times since there only can accept once in [http_client_fake](https://github.com/maximilien/softlayer-go/blob/master/client/fakes/http_client_fake.go#L131). I suggest to make a simple enhancement to set a new array variable like ```DoRawHttpRequestInts    []int``` (We can't change the existing [DoRawHttpRequestInt](https://github.com/maximilien/softlayer-go/blob/master/client/fakes/http_client_fake.go#L11) to keep backward compatibility), and handle this array variable similar to [DoRawHttpRequestResponses](https://github.com/maximilien/softlayer-go/blob/master/client/fakes/http_client_fake.go#L138). Then we could have a chance to test ```bosh-softlayer-cpi``` functions with setting multiple http codes, especially in retryable code like [this](https://github.com/mattcui/bosh-softlayer-cpi/blob/find_stemcell/softlayer/stemcell/softlayer_finder.go#L31). What do you think? Thanks.

**Comment by maximilien** [comment]
Ok sounds good. Send me a PR.
