### ISSUE TITLE
Allow users to choose to use internal or external api endpoint.

### ISSUE THREAD

**Issue by mattcui** [maximilien/softlayer-go#118]
We noticed that the internal softlayer api endpoint (api.service.softlayer.com) is more stable than the external most of the time. Currently, the softlayer-go only uses the external api endpoint, I think there should give users a chance to choose to use the internal or the external endpoint.  A solution is that softlayer-go can set the endpoint reading from a system variable like "SL_API_ENDPOINT_URL", the default value should still be the external endpoint we are using currently. @maximilien  What do you think? Thanks.

**Comment by maximilien** [comment]
Sounds good. Send a PR, should not be hard to do.

**Comment by mattcui** [comment]
@maximilien submitted [PR 119](https://github.com/maximilien/softlayer-go/pull/119) for review and merge. Thanks.

**Comment by maximilien** [comment]
Closing since PR #119 is addressing. Cheers 👍
