### ISSUE TITLE
Need retries for SL API requests which are failed due to i/o timeout

### ISSUE THREAD

**Issue by mattcui** [maximilien/softlayer-go#121]
SL API endpoint is unstable today, saw the timeout error many times during the deployment.

```
dial tcp 66.228.119.120:443: i/o timeout 
```

It's better to re-send the request to SL (maybe 3 or more times) if there returned i/o timeout error. Probably need to add retry code in [http_client.go](https://github.com/maximilien/softlayer-go/blob/master/client/http_client.go#L167), @maximilien what do you think? We need to address this issue in eCPI v2. Thanks.

**Comment by cppforlife** [comment]
be careful here. cant necessarily retry all request that have io timeout since you wouldnt know how far you got.

this one is safe to retry since dial-ing failed. so i would check for "dial tcp".

**Comment by mattcui** [comment]
@cppforlife Thanks for your care, we have a story to (improve error handling and retry strategy)[https://www.pivotaltracker.com/story/show/124447931] planned in Softlayer CPI v3 release, for v2 release, we just want to have a quick patch for this "i/o timeout" issue.

**Comment by maximilien** [comment]
See my comments in your PR @mattcui

**Comment by maximilien** [comment]
I am closing this as done. Please reopen if still there.
