### ISSUE TITLE
Need incorrect size check for network storage service

### ISSUE THREAD

**Issue by zhanghua** [maximilien/softlayer-go#23]
`CreateIscsiVolume(size int, location string)` method of SoftLayer network service should check the negative value of size.

**Comment by maximilien** [comment]
I completed this. However, there are more tests to be added for the whole `SoftLayer_Network_Storage_Service#CreateIscsiVolume()` and `SoftLayer_Network_Storage_Service#DeleteIscsiVolume()` methods.

Creating issue #25 for this and assigning it to you @zhanghua
