### ISSUE TITLE
Backfill tests for SoftLayer_Network_Storage_Service#<Create|Delete>IscsiVolume methods

### ISSUE THREAD

**Issue by maximilien** [maximilien/softlayer-go#29]
Service `SoftLayer_Network_Storage_Service` is missing unit tests for methods `#CreateIscsiVolume()` and `#DeleteIscsiVolume()`.

@zhang-hua  please add appropriate contexts and tests.

Thanks.

**Comment by maximilien** [comment]
So I guess this is still an issue, see #30

**Comment by maximilien** [comment]
Hi, @zhang-hua,

Can you please let us know if there are tracker issues for this or whether you have addressed this lack of test.

Thanks,

@posijon and @maximilien

**Comment by maximilien** [comment]
Hi, @zhang-hua, 

What is the status on this issue? Maybe you can help the CPI team create a chore on this so it is addressed.

Thanks,

max

**Comment by zhang-hua** [comment]
@maximilien ok.

**Comment by maximilien** [comment]
Nice, thanks @zhang-hua, please add Tracker story number to your comment for reference. Thanks.

**Comment by maximilien** [comment]
@jianqiu and @zhang-hua,

Does your recent PR #38 solve this issue? Should I assign this to you @jianqiu?

Thanks,

@maximilien

**Comment by maximilien** [comment]
Hi, @jianqiu, 

Doing some cleanup. Did you solve this issue already? I am planning to close, unless I hear otherwise within 24 hours.

Thanks,

@maximilien

/cc: @zhang-hua

**Comment by jianqiu** [comment]
Hi, @maximilien 

Please hold on, this issue is not resolved yet, I still need one more day to fix it, once it is done, I will keep you update.

Thanks,

/cc: @zhang-hua

**Comment by maximilien** [comment]
Ok cool. Thanks @jianqiu. Best.

**Comment by maximilien** [comment]
Any update on this @jianqiu?

**Comment by maximilien** [comment]
@jianqiu was this resolve? Can I close this? Thanks.

**Comment by maximilien** [comment]
Tired of waiting on this. Closing. Reopen if needed.
