### ISSUE TITLE
complete VirtualStorage APIs

### ISSUE THREAD

**Issue by maximilien** [maximilien/softlayer-go#3]
Complete SL Virtual Storage to at least do the following:

1) List all Virtual Storage objects
2) Create a new Virtual Storage
3) Attach and Detach a Virtual Storage to a Virtual Guest
4) Delete a Virtual Storage that is detached from it's Virtual Guest

**Comment by maximilien** [comment]
Is this issue completed and resolved?

**Comment by xingzhou** [comment]
this is done, closing it
