### ISSUE TITLE
Remove dependency on ssh key file

### ISSUE THREAD

**Issue by posijon** [maximilien/softlayer-go#32]
Tests depend on environmental variables SOFTLAYER_GO_TEST_SSH_KEY_PATH1 and SOFTLAYER_GO_TEST_SSH_KEY_PATH2. Let's instead have tests create, upload, and remove keys that they need, so we don't rely on an external ssh key file. Also applies to bosh-softlayer-cpi.

**Comment by maximilien** [comment]
This is done. The work is in a92ba9ecd77acd887c35a0c9a5e90dca26225e2a
