### ISSUE TITLE
Virtual Guest Lifecycle Test on on Concourse Softlayer VM - Set VM Metadata test for softlayer-go

### ISSUE THREAD

**Issue by posijon** [maximilien/softlayer-go#44]
Failing the integration test on Concourse with this test enabled, so it's disabled temporarily as seen in PR #41 
See Tracker ID (https://www.pivotaltracker.com/story/show/99100866)[#99100866]

**Comment by maximilien** [comment]
Same here @posijon is this still valid? Thanks.

/cc @swetharepakula

**Comment by maximilien** [comment]
I am closing this as no longer valid. Please reopen if we see it again.

/cc @karafelix
