### ISSUE TITLE
Question about using existing SSH keys

### ISSUE THREAD

**Issue by danielcbright** [maximilien/softlayer-go#68]
I would like to build a ```SoftLayer_Virtual_Guest_Template``` that utilizes existing SSH keys that are already in SoftLayer rather than passing a new one every time. Does the current functionality support this? If so, how should I declare that my new virtual server utilizes the existing SSH key?

Thanks

**Comment by maximilien** [comment]
Yes, I think you'd need to find the ID of the existing SSH key and add the ID to the section that has the array of key IDs.

I'll close this issue but if above does not work please reopen. Best.
