### ISSUE TITLE
How to detemine virtual guest is ready to access in softlayer-go?

### ISSUE THREAD

**Issue by cheyang** [maximilien/softlayer-go#92]
I think it's great to use CreateObject to create softlayer virtual guest, then I think I need to check if the virtual guest is ready to use. Can you help me know how to use softlayer-go to check? Thanks.

**Comment by maximilien** [comment]
See [`WaitForVirtualGuest(...)`](https://github.com/maximilien/softlayer-go/blob/master/test_helpers/test_helpers.go#L452) and the next method which waits for the virtual guest to be active.

**Comment by cheyang** [comment]
Thanks
